### ISSUE TITLE
ZZZ seems to glitch with graphical wayland sessoions

### ISSUE THREAD

**Issue by godalming123** [void-linux/void-runit#105]
When I run `zzz` in DWL my system shows DWL after being resumed but cannot be used and is frozen; I cannot switch TTY, move my mouse or use any keybindings. It is possible this is a DWL issue as it handles all of these things and ZZZ seems to work in a tty although if I run zzz in a TTY and then launch dwl my system also freezes.

**Comment by leahneukirchen** [comment]
I have no idea what DWL is but it could be that your graphics driver is locking up resume?

**Comment by godalming123** [comment]
DWL is a wayland compositor.

**Comment by Zapeth** [comment]
Are you by chance using `tlp` on your system? If yes it might be fixed with [this PR](https://github.com/void-linux/void-packages/pull/40534) (not sure why it hasn't been merged yet), or try to disable the service and see if you still get freezes (see also https://github.com/void-linux/void-packages/issues/33813)

**Comment by godalming123** [comment]
Depends if TLP is installed by default on void, I am no longer running that system and so cannot test this for you. So feel free to close this if you want because we cannot check if it has been fixed. I also might switch back to void at some point in which case I will update you.
